"""Send a fake card-issuer alert into the agent mailbox, to test the card parser.

    ./.venv/bin/python examples/send_fake_card_alert.py               # $150.00 at a fake merchant
    ./.venv/bin/python examples/send_fake_card_alert.py 12.34 "STARBUCKS #1234"

No bank is involved; this is an email that looks like Chase's alert. Amounts
over 100 also exercise the money_over_threshold alert rule.
"""

import smtplib
import sys
import time
from email.message import EmailMessage
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from config import email_settings  # noqa: E402

settings = email_settings()
if not settings:
    sys.exit("Not configured: copy .env.example to .env and fill in RECEIPT_IMAP_USER / RECEIPT_IMAP_PASSWORD.")

amount = sys.argv[1] if len(sys.argv) > 1 else "150.00"
merchant = sys.argv[2] if len(sys.argv) > 2 else "ACME CLOUD SERVICES"

msg = EmailMessage()
msg["From"] = settings["user"]
msg["To"] = settings["user"]
msg["Subject"] = f"Your ${amount} transaction with {merchant}"
msg["Message-ID"] = f"<fake-alert-{int(time.time())}@agent-receipt>"
msg.set_content(
    f"You made a ${amount} transaction with {merchant}\n\n"
    f"Card ending in 4242\nDate: {time.strftime('%b %d, %Y at %I:%M %p')}\n\n"
    "This is a simulated alert generated by examples/send_fake_card_alert.py.\n"
)

with smtplib.SMTP(settings["smtp_host"], settings["smtp_port"], timeout=30) as smtp:
    smtp.starttls()
    smtp.login(settings["user"], settings["password"])
    smtp.send_message(msg)
print(f"sent fake alert: ${amount} at {merchant}")
